In [19]:
# NUMPY
import numpy as np

a  = np.array([0,1,2,3,4,5,6,7])
a2 = np.array([[0,1,2,3],[4,5,6,7]])
f  = np.array([0,1,2,3,4,5,6,7], dtype = np.float64) # float
f1 = np.array([0.1,1,2,3,4,5,6,7])                   # float
c  = np.array([0,1,2,3,4,5,6,7], dtype = complex)    # complex


print("a.ndim :",a.ndim) # ndim : n dimensional array              ndim
print("a2.ndim :",a2.ndim)                                     
print("a.itemsize :",a.itemsize)  # byte size of each element      itemsize
print("a.dtype :",a.dtype) # datatype                              dtype
print("f.dtype :",f.dtype) 
print("f1.dtype :",f1.dtype) 
print("c.dtype :",c.dtype) 
print("a.size :",a.size)    # no. of items                         size
print(a2)
print("a2.shape :",a2.shape)  # shape                              shape
print(c)

a.ndim : 1
a2.ndim : 2
a.itemsize : 4
a.dtype : int32
f.dtype : float64
f1.dtype : float64
c.dtype : complex128
a.size : 8
[[0 1 2 3]
 [4 5 6 7]]
a2.shape : (2, 4)
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j]


In [35]:
z = np.zeros((4,3))        # zeros
o = np.ones((4,3))         # ones

print(z)
print(o)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
l = range(5)
a = np.arange(1,6)

b = np.arange(0,10,2)
f = np.linspace(0,5,10)

print(l)
print(l[4])  # not  l[5]
print(a) 
print(b)
print(f)

range(0, 5)
4
[1 2 3 4 5]
[0 2 4 6 8]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [52]:
a = np.array([[0,1],[2,3],[4,5]])
print(a.shape)
print(a)
b = a.reshape(2,3)
print(b.shape)
print(b)
c = a.reshape(6,1)
print(c.shape)
print(c)
d = c.ravel()   # flatten aray
print(d)
print(c)       # didn't touch the original array

(3, 2)
[[0 1]
 [2 3]
 [4 5]]
(2, 3)
[[0 1 2]
 [3 4 5]]
(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[0 1 2 3 4 5]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [54]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [70]:
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis = 0))
print(a.sum(axis = 1))   # cannot 2

b = np.array([1,4,9,17,25])
s = np.sqrt(b)
print("sqrt :",s)
t = np.std(b)
print("standard deviation :",t)

0
5
15
[6 9]
[1 5 9]
sqrt : [1.         2.         3.         4.12310563 5.        ]
standard deviation : 8.772684879784524


In [1]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Addition of 2 array :\n",x+y)   # arithmatic opr -> *,-,/, etc
print("Division of 2 array :\n",x/y)
print("Multiplication of 2 matrices : \n",a.dot(b))

NameError: name 'np' is not defined